version: "3.9"
services:
  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - redis:/data
    networks:
      - stori_networks

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_NAME=root
    networks:
      - stori_networks

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

  api:
    build:
      context: .
      dockerfile: Dockerfile

    env_file: .env
    stdin_open: true
    tty: true
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - stori_networks
    links:
      - db:db
    ports:
      - "8020:8010"
      - "5555:5555"

networks:
  stori_networks:
    driver: bridge
volumes:
  redis: {}
